# -*- coding: utf-8 -*-
"""dos-Pentagrafeno-PW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XMzVteZgH3KChatlURfzq6G1aYb7vmnu
"""

from ase import Atoms
from ase.io import read
from gpaw import GPAW, PW,FermiDirac
from ase.optimize import BFGS
from ase.constraints import ExpCellFilter
import matplotlib.pyplot as plt
# Density of States

label = 'PW-'
calc = GPAW('PW_Penta_gs.gpw',fixdensity=True,
            nbands= "nao", 
            kpts=(10,10,1),
            txt='PG-DOS-PW.log')

calc.get_potential_energy()
e, dos = calc.get_dos(spin=0, npts=2001, width=0.2)
e_f = calc.get_fermi_level()
fig, ax= plt.subplots()
ax.plot(e - e_f, dos)
plt.axis([-5, 5, None, 4])
plt.ylabel('DOS')
fig.savefig(label+"DOS-PG.png")
#plt.close()
