# -*- coding: utf-8 -*-
"""FosforenoCluster.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jykPc7XYDr_mWzP3SPKX9zIFVz-YVthZ
"""

from ase import Atoms
from ase.visualize.plot import plot_atoms
from gpaw import GPAW,PW,FermiDirac
from math import sqrt
import matplotlib.pyplot as plt
from ase.optimize import BFGS
from ase.constraints import ExpCellFilter
from  ase.io  import  read


#Ahora calculamos las bandasssssssss -------------------------------------
calc = GPAW('phosphorene-gs.gpw',fixdensity=True,
            nbands= "nao",
            symmetry='off', 
            kpts={'path':'GXX1YGX1','npoints':200}, 
            convergence={'bands': 24},
            parallel = {"sl_auto":True},#cuantas bandas va a converger. 4 bandas ocupadas y 4 desocupadas
            txt='phos-bs.log')
#---------------------------------------
#  run 
#---------------------------------------
calc.get_potential_energy()
bs = calc.band_structure()
bs.plot(filename="bandstructure.png", show=False, emax=10.0)
print("Bandas ok")

